### ISSUE TITLE
Re-enabling navigation at start does not work properly

### ISSUE THREAD

**Issue by woody4165** [shmykelsa/AA-Tweaker#8]
Hi

I've reverted back this option to have navigation at start, but ai still see the main menu. I've tried leaving Maps or waze before removing cable from phone to close AA, but no luck...

Apparently no errrors in log...

What can I check?

Thanks

**Comment by shmykelsa** [comment]
Hi,

As of now, when you revert a command with AA AIO TWEAKER, the app does not really revert, but instead it deleted the trigger that was created in order to preserve the persistence of the tweak.

Once the trigger is deleted, Google Play Services should re-build the flags that manager that functionality. This operation can also take a couple of days to be made, and there's no method, as of now, to force a re-build.

This behaviour could be fixed by simply putting back the flags into the database, but it will take me some time.

Please let me know if this behaviour is not fixed after 3-4 days and I'll work it out.

**Comment by woody4165** [comment]
Thanks Gabriele.

After less than 24hrs all is ok.

I was not aware of this...
