### ISSUE TITLE
Play protect

### ISSUE THREAD

**Issue by jk1526** [shmykelsa/AA-Tweaker#80]
App is triggering warning on play protect.
" This app tries to bypass Androids security protections"

**Comment by shmykelsa** [comment]
Little can be done about it.

AA AIO TWEAKER does not contain any malware. Google obviously doesn't like Android Auto modding because of driving security. If you want to avoid any warning you'd want to know that Google Play Protect does not really have any anti-virus feature, rather it just warns of apps that Google doesn't like because of various reasons.
